### ISSUE TITLE
BadMethodCallException: Method clone does not exist. in /app/vendor/nesbot/carbon/src/Carbon/Carbon.php

### ISSUE THREAD

**Issue by wolf-em** [solspace/craft-calendar#101]
Trying to update a local copy of a Craft site to php 8.0 and encountering an internal server error caused by a missing clone method in the nesbot/carbon dependency. Deleted the vender folder and ran composer update so that the calendar plugin is up to version 3.3.8, but still running into the same issue.

Here's the stack trace: 

2022-02-14 09:53:14 [-][10979][2e5b942e7420c5b2315ffea44fad646f][error][BadMethodCallException] BadMethodCallException: Method clone does not exist. in /app/vendor/nesbot/carbon/src/Carbon/Carbon.php:5377
Stack trace:
#0 /app/vendor/solspace/craft3-calendar/packages/plugin/src/Elements/Db/EventQuery.php(1376): Carbon\Carbon->__call('clone', Array)
#1 /app/vendor/solspace/craft3-calendar/packages/plugin/src/Elements/Db/EventQuery.php(535): Solspace\Calendar\Elements\Db\EventQuery->cacheEvents()
#2 /app/vendor/twig/twig/src/Extension/CoreExtension.php(1566): Solspace\Calendar\Elements\Db\EventQuery->all()
#3 /app/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(Solspace\Calendar\Elements\Db\EventQuery), 'all', Array, 'method', false, false)
#4 /app/storage/runtime/compiled_templates/29/29034fa39ee657a6063bea6ab081780e01228102da1a9ffb5d8afe2ea70ebb2a.php(89): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(Solspace\Calendar\Elements\Db\EventQuery), 'all', Array, 'method')
#5 /app/vendor/twig/twig/src/Template.php(405): __TwigTemplate_6e0b7fd77cb6ab84d5e344191e7b59faaa1717ca6a8cbdf30bbf892c44a6b390->doDisplay(Array, Array)
#6 /app/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#7 /app/storage/runtime/compiled_templates/78/78f45de3e43fbbe3ca3a187e6c7154566479e371c918d476625fea52ee2c1e26.php(92): Twig\Template->display(Array)
#8 /app/vendor/twig/twig/src/Template.php(182): __TwigTemplate_61c54d75e34fd2cd980e6f596e39269cc671c216b36512ea5ac3ef54c1ee1e5c->block_content(Array, Array)
#9 /app/storage/runtime/compiled_templates/c4/c4575b7b430a619eafc2c13b67fe2534f514d9ce8172c14cfb565e656662d98c.php(337): Twig\Template->displayBlock('content', Array, Array)
#10 /app/vendor/twig/twig/src/Template.php(405): __TwigTemplate_5a15aec3d4a2d2bdbb15d7f8144942bbc88eefb7ab25a1d251a4afc89962b697->doDisplay(Array, Array)
#11 /app/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /app/storage/runtime/compiled_templates/78/78f45de3e43fbbe3ca3a187e6c7154566479e371c918d476625fea52ee2c1e26.php(44): Twig\Template->display(Array, Array)
#13 /app/vendor/twig/twig/src/Template.php(405): __TwigTemplate_61c54d75e34fd2cd980e6f596e39269cc671c216b36512ea5ac3ef54c1ee1e5c->doDisplay(Array, Array)
#14 /app/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /app/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#16 /app/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#17 /app/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#18 /app/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('index.html', Array)
#19 /app/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate('index.html', Array)
#20 /app/vendor/craftcms/cms/src/web/Controller.php(201): craft\web\View->renderPageTemplate('index.html', Array, 'site')
#21 /app/vendor/craftcms/cms/src/controllers/TemplatesController.php(102): craft\web\Controller->renderTemplate('index.html', Array)
#22 [internal function]: craft\controllers\TemplatesController->actionRender('index.html', Array)
#23 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#24 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#25 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('render', Array)
#26 /app/vendor/craftcms/cms/src/web/Application.php(292): yii\base\Module->runAction('templates/rende...', Array)
#27 /app/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#28 /app/vendor/craftcms/cms/src/web/Application.php(277): yii\web\Application->handleRequest(Object(craft\web\Request))
#29 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#30 /app/public/index.php(21): yii\base\Application->run()
#31 {main}
2022-02-14 09:53:13 [-][10979][2e5b942e7420c5b2315ffea44fad646f][info][application] $_GET = []

$_POST = []

$_FILES = []

$_COOKIE = [
    '_aeaid' => '6413cc36-c94c-4087-a5e9-877c6de4e648'
    'aelastsite' => 'vwFceMPSTA4d9Yr35rlQI3Qs1O9KVYldyNg2C+DmA3fKok0FFHsS8aIoyXk5apHQ'
    '1031b8c41dfff97a311a7ac99863bdc5_username' => 'cbdda40ad839e5858f9993861ac7c9203c13afcdcbe80d1157b697bbf9578643a:2:{i:0;s:41:\"1031b8c41dfff97a311a7ac99863bdc5_username\";i:1;s:7:\"wolf.em\";}'
    '__stripe_mid' => '8b32c5bf-d12d-4449-a1bd-c84c3222cafaae6032'
    '1031b8c41dfff97a311a7ac99863bdc5_identity' => '9f05c7add486ec28abc10b60a3fb2498090c4b720f93125f760b3ec9fe68a332a:2:{i:0;s:41:\"1031b8c41dfff97a311a7ac99863bdc5_identity\";i:1;s:163:\"[10979,\"[\\\"E3AOsBEJROWuSkzUhg1V2qKhDuztx34iSfi1mxQ8iVtrG76WXtx6wOmyvv-4I0fw81g1570r3vPJAl_ceVAYmKFudMLWFcU_DKNA\\\",null,\\\"bdc7b89c990986635b818761ee28c3fc\\\"]\",3600]\";}'
    'CRAFT_CSRF_TOKEN' => '•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'CraftSessionId' => '2e5b942e7420c5b2315ffea44fad646f'
]

$_SESSION = [
    'bd62416aa8538ede709019a5e113eea5__flash' => []
    '1031b8c41dfff97a311a7ac99863bdc5__token' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    '1031b8c41dfff97a311a7ac99863bdc5__id' => 10979
    '__authKey' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    '1031b8c41dfff97a311a7ac99863bdc5__expire' => 1644857593
    '__duration' => 3600
]

$_SERVER = [
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    'HOSTNAME' => 'dec74eeba972'
    'COMPOSER_HOME' => '/tmp'
    'PHP_DISPLAY_ERRORS' => 'on'
    'PHP_MEMORY_LIMIT' => '512M'
    'PHP_MAX_EXECUTION_TIME' => '5000'
    'PHP_UPLOAD_MAX_FILESIZE' => '512M'
    'PHP_MAX_INPUT_VARS' => '5000'
    'PHP_POST_MAX_SIZE' => '512M'
    'PHP_OPCACHE_ENABLE' => '0'
    'PHP_OPCACHE_REVALIDATE_FREQ' => '0'
    'PHP_OPCACHE_VALIDATE_TIMESTAMPS' => '0'
    'XDEBUG_SESSION' => 'PHPSTORM'
    'PHP_IDE_CONFIG' => 'serverName=lwi.nitro'
    'XDEBUG_MODE' => 'off'
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev dpkg 		file 		g++ 		gcc 		libc-dev 		make 		pkgconf 		re2c'
    'PHP_INI_DIR' => '/usr/local/etc/php'
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    'PHP_LDFLAGS' => '-Wl,-O1 -pie'
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F'
    'PHP_VERSION' => '8.0.14'
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.14.tar.xz'
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.14.tar.xz.asc'
    'PHP_SHA256' => 'fbde8247ac200e4de73449d9fefc8b495d323b5be9c10cdb645fb431c91156e3'
    'PHP_OPCACHE_MAX_ACCELERATED_FILES' => '10000'
    'PHP_OPCACHE_MEMORY_CONSUMPTION' => '128'
    'PHP_OPCACHE_MAX_WASTED_PERCENTAGE' => '10'
    'PHP_OPCACHE_INTERNED_STRINGS_BUFFER' => '16'
    'PHP_OPCACHE_FAST_SHUTDOWN' => '1'
    'MOZJPEG_VERSION' => '3.3.1'
    'MOZJPEG_BUILD_DEPS' => 'autoconf     automake     build-base     libtool     nasm     pkgconf     tar'
    'LD_PRELOAD' => '/usr/lib/preloadable_libiconv.so'
    'HOME' => '/home/www-data'
    'SUPERVISOR_ENABLED' => '1'
    'SUPERVISOR_PROCESS_NAME' => 'php-fpm'
    'SUPERVISOR_GROUP_NAME' => 'php-fpm'
    'USER' => 'www-data'
    'HTTP_X_FORWARDED_PROTO' => 'https'
    'HTTP_X_FORWARDED_FOR' => '172.18.0.1'
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1'
    'HTTP_SEC_FETCH_USER' => '?1'
    'HTTP_SEC_FETCH_SITE' => 'same-origin'
    'HTTP_SEC_FETCH_MODE' => 'navigate'
    'HTTP_SEC_FETCH_DEST' => 'document'
    'HTTP_SEC_CH_UA_PLATFORM' => '\"Windows\"'
    'HTTP_SEC_CH_UA_MOBILE' => '?0'
    'HTTP_SEC_CH_UA' => '\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"98\", \"Microsoft Edge\";v=\"98\"'
    'HTTP_REFERER' => 'https://lwi.nitro/admin/dashboard'
    'HTTP_COOKIE' => '_aeaid=6413cc36-c94c-4087-a5e9-877c6de4e648; aelastsite=vwFceMPSTA4d9Yr35rlQI3Qs1O9KVYldyNg2C%2BDmA3fKok0FFHsS8aIoyXk5apHQ; 1031b8c41dfff97a311a7ac99863bdc5_username=cbdda40ad839e5858f9993861ac7c9203c13afcdcbe80d1157b697bbf9578643a%3A2%3A%7Bi%3A0%3Bs%3A41%3A%221031b8c41dfff97a311a7ac99863bdc5_username%22%3Bi%3A1%3Bs%3A7%3A%22wolf.em%22%3B%7D; __stripe_mid=8b32c5bf-d12d-4449-a1bd-c84c3222cafaae6032; 1031b8c41dfff97a311a7ac99863bdc5_identity=9f05c7add486ec28abc10b60a3fb2498090c4b720f93125f760b3ec9fe68a332a%3A2%3A%7Bi%3A0%3Bs%3A41%3A%221031b8c41dfff97a311a7ac99863bdc5_identity%22%3Bi%3A1%3Bs%3A163%3A%22%5B10979%2C%22%5B%5C%22E3AOsBEJROWuSkzUhg1V2qKhDuztx34iSfi1mxQ8iVtrG76WXtx6wOmyvv-4I0fw81g1570r3vPJAl_ceVAYmKFudMLWFcU_DKNA%5C%22%2Cnull%2C%5C%22bdc7b89c990986635b818761ee28c3fc%5C%22%5D%22%2C3600%5D%22%3B%7D; CRAFT_CSRF_TOKEN=fd90ecdcbfe36b39497cad0f11be78d67a6276c734eb20dfd3daf8fc1a79b133a%3A2%3A%7Bi%3A0%3Bs%3A16%3A%22CRAFT_CSRF_TOKEN%22%3Bi%3A1%3Bs%3A212%3A%22f1HR7oBsNqU0DgOffRmND2K_ghQJAvpwXzSmzRZN%7Cac93630ef08bc19844ece15f3c2112a2b41f79d4d1346eba511d6fc473f2d9dbf1HR7oBsNqU0DgOffRmND2K_ghQJAvpwXzSmzRZN%7C10979%7C%242y%2413%24WgIUDkNmQfeGJP50PESBQePToM.bkkqboltGaxbbLi1%2FgzXYxmR4e%22%3B%7D; CraftSessionId=2e5b942e7420c5b2315ffea44fad646f'
    'HTTP_CACHE_CONTROL' => 'max-age=0'
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br'
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.50'
    'HTTP_HOST' => 'lwi.nitro'
    'SCRIPT_FILENAME' => '/app/public/index.php'
    'REDIRECT_STATUS' => '200'
    'SERVER_NAME' => '_'
    'SERVER_PORT' => '8080'
    'SERVER_ADDR' => '172.18.0.2'
    'REMOTE_PORT' => '55190'
    'REMOTE_ADDR' => '172.18.0.9'
    'SERVER_SOFTWARE' => 'nginx/1.20.2'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'REQUEST_SCHEME' => 'http'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'DOCUMENT_ROOT' => '/app/public'
    'DOCUMENT_URI' => '/index.php'
    'REQUEST_URI' => '/'
    'SCRIPT_NAME' => '/index.php'
    'CONTENT_LENGTH' => ''
    'CONTENT_TYPE' => ''
    'REQUEST_METHOD' => 'GET'
    'QUERY_STRING' => ''
    'FCGI_ROLE' => 'RESPONDER'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1644853993.0036
    'REQUEST_TIME' => 1644853993
    'argv' => []
    'argc' => 0
    'APP_ID' => 'CraftCMS--6b322f80-7061-42e5-9c8b-961553a0dde3'
    'SECURITY_KEY' => '••••••••••••••••••••••••••••••••'
    'DB_DRIVER' => 'mysql'
    'DB_SERVER' => 'mysql-8.0-3306.database.nitro'
    'DB_PORT' => '3306'
    'DB_DATABASE' => 'lwi'
    'DB_USER' => 'nitro'
    'DB_PASSWORD' => '•••••'
    'DB_SCHEMA' => ''
    'DB_TABLE_PREFIX' => ''
    'PRIMARY_SITE_URL' => 'lwi.nitro'
    'SITE_URL' => 'https://lwi.nitro/'
    'SERVD_PROJECT_SLUG' => 'lawatershed-initiative'
    'SERVD_SECURITY_KEY' => '••••••••••••••••••••••••••••••••'
    'SERVD_ASSETS_ENVIRONMENT' => 'staging'
    'VUE_DEVTOOLS_HOST' => '127.0.0.1'
    'VUE_DEVTOOLS_PORT' => '8098'
]

**Comment by wolf-em** [comment]
Another outdated plugin was requiring carbon 1, so we just removed it.
