### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by boboldehampsink** [solspace/craft-calendar#103]
**Describe the bug or issue you're experiencing**

EventQuery.php implements both QueryException and Countable. They are not compatible according to PHP 8.1 and the plugin is not usable.

```
During inheritance of Countable: Uncaught yii\base\ErrorException: Return type of yii\db\QueryInterface::count($q = '*', $db = null) should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/user/vendor/yiisoft/yii2/db/QueryInterface.php:49
```

**Comment by boboldehampsink** [comment]
Any response? Can't use this plugin at all on PHP 8.1...

**Comment by kjmartens** [comment]
Hi @boboldehampsink,

Sorry for the delay... we're going to check into this one soon and ensure Calendar is compatible with PHP 8.1. 🙂

**Comment by kjmartens** [comment]
This should now be corrected in 3.3.9. 🙂

**Comment by boboldehampsink** [comment]
Thanks!

**Comment by boboldehampsink** [comment]
Still seeing this error wiwth 3.3.9!

```
PHP Fatal Error 'yii\base\ErrorException' with message 'During inheritance of Countable: Uncaught yii\base\ErrorException: Return type of yii\db\QueryInterface::count($q = '*', $db = null) should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/user/vendor/yiisoft/yii2/db/QueryInterface.php:49
```

**Comment by kjmartens** [comment]
@boboldehampsink Is this happening for you anywhere you load Calendar? Or is it a specific template for function you're running, etc? We're unable to duplicate this on our end, so perhaps we're testing a little differently. I'm curious if, for example, the demo templates included with Calendar also trigger this error?

**Comment by boboldehampsink** [comment]
@kjmartens it happens when I try to add a Yii event to the EventQuery class:

```
use craft\events\CancelableEvent;
use Solspace\Calendar\Elements\Db\EventQuery;
use yii\base\Event;

Event::on(EventQuery::class, EventQuery::EVENT_AFTER_PREPARE, function (CancelableEvent $e) {
   ...
});
```

Just autoloading the eventquery class already generates this error. Here is the full stacktrace:

```
<pre>PHP Fatal Error 'yii\base\ErrorException' with message 'During inheritance of Countable: Uncaught yii\base\ErrorException: Return type of yii\db\QueryInterface::count($q = '*', $db = null) should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/user/vendor/yiisoft/yii2/db/QueryInterface.php:49
--
  | Stack trace:
  | #0 /app/user/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler-&gt;handleError(8192, 'Return type of ...', '/app/user/vendo...', 49)
  | #1 /app/user/vendor/craftcms/cms/src/elements/db/ElementQueryInterface.php(29): craft\web\ErrorHandler-&gt;handleError(8192, 'Return type of ...', '/app/user/vendo...', 49)
  | #2 /app/user/vendor/composer/ClassLoader.php(571): include('/app/user/vendo...')
  | #3 /app/user/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/app/user/vendo...')
  | #4 /app/user/vendor/craftcms/cms/src/elements/db/ElementQuery.php(51): Composer\Autoload\ClassLoader-&gt;loadClass('craft\\elements\\...')
  | #5 /app/user/vendor/composer/ClassLoader.php(571): include('/app/user/vendo...')
  | #6 /app/user/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/app/user/vendo...')
  | #7 /app/user/vendor/solspace/craft3-calendar/packages/plugin/src/Elements/Db/EventQuery.php(27): Composer\Autoload\ClassLoader-&gt;loadClass('craft\\elements\\...')
  | #8 /app/user/vendor/composer/ClassLoader.php(571): include('/app/user/vendo...')
  | #9 /app/user/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/app/user/vendo...')
  | #10 /app/user/modules/calendar/Module.php(31): Composer\Autoload\ClassLoader-&gt;loadClass('Solspace\\Calend...')
  | #11 /app/user/vendor/yiisoft/yii2/base/BaseObject.php(109): modules\calendar\Module-&gt;init()
  | #12 /app/user/vendor/yiisoft/yii2/base/Module.php(161): yii\base\BaseObject-&gt;__construct(Array)
  | #13 [internal function]: yii\base\Module-&gt;__construct('calendar', Object(craft\web\Application), Array)
  | #14 /app/user/vendor/yiisoft/yii2/di/Container.php(411): ReflectionClass-&gt;newInstanceArgs(Array)
  | #15 /app/user/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container-&gt;build('modules\\calenda...', Array, Array)
  | #16 /app/user/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container-&gt;get('modules\\calenda...', Array)
  | #17 /app/user/vendor/yiisoft/yii2/base/Module.php(445): yii\BaseYii::createObject('modules\\calenda...', Array)
  | #18 /app/user/vendor/yiisoft/yii2/base/Application.php(313): yii\base\Module-&gt;getModule('calendar')
  | #19 /app/user/vendor/craftcms/cms/src/web/Application.php(116): yii\base\Application-&gt;bootstrap()
  | #20 /app/user/vendor/yiisoft/yii2/base/Application.php(271): craft\web\Application-&gt;bootstrap()
  | #21 /app/user/vendor/craftcms/cms/src/web/Application.php(93): yii\base\Application-&gt;init()
  | #22 /app/user/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application-&gt;init()
  | #23 /app/user/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject-&gt;__construct(Array)
  | #24 [internal function]: yii\base\Application-&gt;__construct(Array)
  | #25 /app/user/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass-&gt;newInstanceArgs(Array)
  | #26 /app/user/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container-&gt;build('craft\\web\\Appli...', Array, Array)
  | #27 /app/user/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container-&gt;get('craft\\web\\Appli...', Array, Array)
  | #28 /app/user/vendor/craftcms/cms/src/Craft.php(61): yii\BaseYii::createObject(Array, Array)
  | #29 /app/user/vendor/craftcms/cms/src/test/TestSetup.php(124): Craft::createObject(Array)
  | #30 /app/user/vendor/craftcms/cms/src/test/Craft.php(121): craft\test\TestSetup::warmCraft()
  | #31 /app/user/vendor/codeception/codeception/src/Codeception/SuiteManager.php(83): craft\test\Craft-&gt;_initialize()
  | #32 /app/user/vendor/codeception/codeception/src/Codeception/Codecept.php(204): Codeception\SuiteManager-&gt;initialize()
  | #33 /app/user/vendor/codeception/codeception/src/Codeception/Codecept.php(162): Codeception\Codecept-&gt;runSuite(Array, 'acceptance', NULL)
  | #34 /app/user/vendor/codeception/codeception/src/Codeception/Command/Run.php(544): Codeception\Codecept-&gt;run('acceptance')
  | #35 /app/user/vendor/codeception/codeception/src/Codeception/Command/Run.php(408): Codeception\Command\Run-&gt;runSuites(Array, Array)
  | #36 /app/user/vendor/symfony/console/Command/Command.php(298): Codeception\Command\Run-&gt;execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  | #37 /app/user/vendor/symfony/console/Application.php(1015): Symfony\Component\Console\Command\Command-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  | #38 /app/user/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application-&gt;doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  | #39 /app/user/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application-&gt;doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  | #40 /app/user/vendor/codeception/codeception/src/Codeception/Application.php(117): Symfony\Component\Console\Application-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  | #41 /app/user/vendor/codeception/codeception/app.php(46): Codeception\Application-&gt;run()
  | #42 /app/user/vendor/codeception/codeception/app.php(47): {closure}()
  | #43 /app/user/vendor/codeception/codeception/codecept(7): require('/app/user/vendo...')
  | #44 /app/user/vendor/bin/codecept(117): include('/app/user/vendo...')
  | #45 {main}'
  |  
  | in /app/user/vendor/craftcms/cms/src/elements/db/ElementQueryInterface.php:29
```

(for context, this stack trace is from running unit tests - which is where i found the error)

**Comment by boboldehampsink** [comment]
@kjmartens any update?

**Comment by boboldehampsink** [comment]
Tried this with dev-master and still seeing the same error:

```
PHP Fatal Error 'yii\base\ErrorException' with message 'During inheritance of Countable: Uncaught yii\base\ErrorException: Return type of yii\db\QueryInterface::count($q = '*', $db = null) should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/user/vendor/yiisoft/yii2/db/QueryInterface.php:49
--
  | Stack trace:
  | #0 /app/user/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler-&gt;handleError(8192, 'Return type of ...', '/app/user/vendo...', 49)
  | #1 /app/user/vendor/craftcms/cms/src/elements/db/ElementQueryInterface.php(29): craft\web\ErrorHandler-&gt;handleError(8192, 'Return type of ...', '/app/user/vendo...', 49)
  | #2 /app/user/vendor/composer/ClassLoader.php(571): include('/app/user/vendo...')
  | #3 /app/user/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/app/user/vendo...')
  | #4 /app/user/vendor/craftcms/cms/src/elements/db/ElementQuery.php(53): Composer\Autoload\ClassLoader-&gt;loadClass('craft\\elements\\...')
  | #5 /app/user/vendor/composer/ClassLoader.php(571): include('/app/user/vendo...')
  | #6 /app/user/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/app/user/vendo...')
  | #7 /app/user/vendor/solspace/craft3-calendar/packages/plugin/src/Elements/Db/EventQuery.php(27): Composer\Autoload\ClassLoader-&gt;loadClass('craft\\elements\\...')
  | #8 /app/user/vendor/composer/ClassLoader.php(571): include('/app/user/vendo...')
  | #9 /app/user/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/app/user/vendo...')
  | #10 /app/user/modules/calendar/Module.php(31): Composer\Autoload\ClassLoader-&gt;loadClass('Solspace\\Calend...')
  | #11 /app/user/vendor/yiisoft/yii2/base/BaseObject.php(109): modules\calendar\Module-&gt;init()
  | #12 /app/user/vendor/yiisoft/yii2/base/Module.php(161): yii\base\BaseObject-&gt;__construct(Array)
  | #13 [internal function]: yii\base\Module-&gt;__construct('calendar', Object(craft\web\Application), Array)
  | #14 /app/user/vendor/yiisoft/yii2/di/Container.php(411): ReflectionClass-&gt;newInstanceArgs(Array)
  | #15 /app/user/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container-&gt;build('modules\\calenda...', Array, Array)
  | #16 /app/user/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container-&gt;get('modules\\calenda...', Array)
  | #17 /app/user/vendor/yiisoft/yii2/base/Module.php(445): yii\BaseYii::createObject('modules\\calenda...', Array)
  | #18 /app/user/vendor/yiisoft/yii2/base/Application.php(313): yii\base\Module-&gt;getModule('calendar')
  | #19 /app/user/vendor/craftcms/cms/src/web/Application.php(116): yii\base\Application-&gt;bootstrap()
  | #20 /app/user/vendor/yiisoft/yii2/base/Application.php(271): craft\web\Application-&gt;bootstrap()
  | #21 /app/user/vendor/craftcms/cms/src/web/Application.php(93): yii\base\Application-&gt;init()
  | #22 /app/user/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application-&gt;init()
  | #23 /app/user/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject-&gt;__construct(Array)
  | #24 [internal function]: yii\base\Application-&gt;__construct(Array)
  | #25 /app/user/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass-&gt;newInstanceArgs(Array)
  | #26 /app/user/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container-&gt;build('craft\\web\\Appli...', Array, Array)
  | #27 /app/user/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container-&gt;get('craft\\web\\Appli...', Array, Array)
  | #28 /app/user/vendor/craftcms/cms/src/Craft.php(61): yii\BaseYii::createObject(Array, Array)
  | #29 /app/user/vendor/craftcms/cms/src/test/TestSetup.php(124): Craft::createObject(Array)
  | #30 /app/user/vendor/craftcms/cms/src/test/Craft.php(121): craft\test\TestSetup::warmCraft()
  | #31 /app/user/vendor/codeception/codeception/src/Codeception/SuiteManager.php(83): craft\test\Craft-&gt;_initialize()
  | #32 /app/user/vendor/codeception/codeception/src/Codeception/Codecept.php(204): Codeception\SuiteManager-&gt;initialize()
  | #33 /app/user/vendor/codeception/codeception/src/Codeception/Codecept.php(162): Codeception\Codecept-&gt;runSuite(Array, 'acceptance', NULL)
  | #34 /app/user/vendor/codeception/codeception/src/Codeception/Command/Run.php(545): Codeception\Codecept-&gt;run('acceptance')
  | #35 /app/user/vendor/codeception/codeception/src/Codeception/Command/Run.php(409): Codeception\Command\Run-&gt;runSuites(Array, Array)
  | #36 /app/user/vendor/symfony/console/Command/Command.php(298): Codeception\Command\Run-&gt;execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  | #37 /app/user/vendor/symfony/console/Application.php(1024): Symfony\Component\Console\Command\Command-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  | #38 /app/user/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application-&gt;doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  | #39 /app/user/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application-&gt;doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  | #40 /app/user/vendor/codeception/codeception/src/Codeception/Application.php(117): Symfony\Component\Console\Application-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  | #41 /app/user/vendor/codeception/codeception/app.php(46): Codeception\Application-&gt;run()
  | #42 /app/user/vendor/codeception/codeception/app.php(47): {closure}()
  | #43 /app/user/vendor/codeception/codeception/codecept(7): require('/app/user/vendo...')
  | #44 /app/user/vendor/bin/codecept(117): include('/app/user/vendo...')
  | #45 {main}'
  |  
  | in /app/user/vendor/craftcms/cms/src/elements/db/ElementQueryInterface.php:29
```

**Comment by boboldehampsink** [comment]
hi @gustavs-gutmanis no extra config, also Countable is removed indeed. But in the end EventQuery extends ElementQuery which implements ElementQueryInterface which implements Countable. So the error is still from Countable because of that.

**Comment by boboldehampsink** [comment]
@gustavs-gutmanis I agree - i will look into this some more and submit a PR if i find something

**Comment by boboldehampsink** [comment]
Added a PR with Craft - https://github.com/craftcms/cms/pull/11344
