### ISSUE TITLE
Error after Update to 3.3.10 - Call to a member function getId() on null

### ISSUE THREAD

**Issue by luke-nehemedia** [solspace/craft-calendar#127]
After updating on 3.3.10 I get the following error message:

> Call to a member function getId() on null

After rolling back to 3.3.9 everything works fine again. 

**This is the complete error message:**
```
2022-04-23 22:53:56 - error - Error

Error: Call to a member function getId() on null in /home/abc/xyz/craft3/vendor/solspace/craft3-calendar/packages/plugin/src/Elements/Event.php:1593
Stack trace:
#0 /home/abc/xyz/craft3/vendor/solspace/craft3-calendar/packages/plugin/src/Elements/Event.php(479): Solspace\Calendar\Elements\Event->addOriginalEventToSelectDates()
#1 /home/abc/xyz/craft3/vendor/solspace/craft3-calendar/packages/plugin/src/Elements/Event.php(549): Solspace\Calendar\Elements\Event->getSelectDates()
#2 /home/abc/xyz/craft3/vendor/solspace/craft3-calendar/packages/plugin/src/Elements/Event.php(704): Solspace\Calendar\Elements\Event->getSelectDatesAsString()
#3 /home/abc/xyz/craft3/vendor/solspace/craft3-calendar/packages/plugin/src/Elements/Event.php(297): Solspace\Calendar\Elements\Event->happensOn()
#4 /home/abc/xyz/craft3/vendor/solspace/craft3-calendar/packages/plugin/src/Elements/Db/EventQuery.php(1242): Solspace\Calendar\Elements\Event->cloneForDate()
#5 /home/abc/xyz/craft3/vendor/solspace/craft3-calendar/packages/plugin/src/Elements/Db/EventQuery.php(1235): Solspace\Calendar\Elements\Db\EventQuery->storeEventOnDate()
#6 /home/abc/xyz/craft3/vendor/solspace/craft3-calendar/packages/plugin/src/Elements/Db/EventQuery.php(531): Solspace\Calendar\Elements\Db\EventQuery->cacheToStorage()
#7 /home/abc/xyz/craft3/vendor/solspace/craft3-calendar/packages/plugin/src/Elements/Db/EventQuery.php(434): Solspace\Calendar\Elements\Db\EventQuery->all()
#8 /home/abc/xyz/craft3/vendor/craftcms/cms/src/db/Paginator.php(130): Solspace\Calendar\Elements\Db\EventQuery->count()
#9 /home/abc/xyz/craft3/vendor/craftcms/cms/src/db/Paginator.php(153): craft\db\Paginator->getTotalResults()
#10 /home/abc/xyz/craft3/vendor/craftcms/cms/src/db/Paginator.php(175): craft\db\Paginator->getTotalPages()
#11 /home/abc/xyz/craft3/vendor/craftcms/cms/src/db/Paginator.php(101): craft\db\Paginator->setCurrentPage()
#12 /home/abc/xyz/craft3/vendor/craftcms/cms/src/helpers/Template.php(141): craft\db\Paginator->__construct()
#13 /home/abc/xyz/craft3/storage/runtime/compiled_templates/21/2157e7c1da64fa500f1c7e0c552215748fa3ffa184261de4024751c84aeabbfb.php(231): craft\helpers\Template::paginateQuery()
#14 /home/abc/xyz/craft3/vendor/twig/twig/src/Template.php(405): __TwigTemplate_010727f9823fcdb05d2d29c98b203b778787f0299ed52d94441f9f69be8b398f->doDisplay()
#15 /home/abc/xyz/craft3/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#16 /home/abc/xyz/craft3/storage/runtime/compiled_templates/0e/0ea2d86bd8cd58d773ddeff2242f3769d7743873070e2fb10d9c1546da9efc2b.php(668): Twig\Template->display()
#17 /home/abc/xyz/craft3/vendor/twig/twig/src/Template.php(405): __TwigTemplate_c716bcd2d5d5adec991529d3d4362b3ffa128a864a587f8a20c89b81af845a85->doDisplay()
#18 /home/abc/xyz/craft3/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#19 /home/abc/xyz/craft3/storage/runtime/compiled_templates/fe/fe5d93ad3819b191310ce87199e7433a1a9d95be6b1c1c93c9550d78a418599f.php(96): Twig\Template->display()
#20 /home/abc/xyz/craft3/vendor/twig/twig/src/Template.php(182): __TwigTemplate_ca8e8f711c147ab2db82908f47b32c2885f0efe4f3f5100db9ad10988a8a3c5b->block_main()
#21 /home/abc/xyz/craft3/storage/runtime/compiled_templates/fc/fc4b20e80251515ddd72d02620beaf4f31f05ffa1ba05498644a19fc3ec649c2.php(406): Twig\Template->displayBlock()
#22 /home/abc/xyz/craft3/vendor/twig/twig/src/Template.php(182): __TwigTemplate_5d0c867d338703f31061ae7e9fdc1aef96786316d29dbf9a57742e208cd23d2d->block_body()
#23 /home/abc/xyz/craft3/storage/runtime/compiled_templates/a6/a64893a9f181c495b84c3c5bd207f88e3f8ec568a2649d848d57c316aaa87730.php(74): Twig\Template->displayBlock()
#24 /home/abc/xyz/craft3/vendor/twig/twig/src/Template.php(405): __TwigTemplate_e48b651cc3fee767fa3f96f6c169bcf29b48f8492b755c339a2a4ca911da2be9->doDisplay()
#25 /home/abc/xyz/craft3/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#26 /home/abc/xyz/craft3/storage/runtime/compiled_templates/fc/fc4b20e80251515ddd72d02620beaf4f31f05ffa1ba05498644a19fc3ec649c2.php(51): Twig\Template->display()
#27 /home/abc/xyz/craft3/vendor/twig/twig/src/Template.php(405): __TwigTemplate_5d0c867d338703f31061ae7e9fdc1aef96786316d29dbf9a57742e208cd23d2d->doDisplay()
#28 /home/abc/xyz/craft3/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#29 /home/abc/xyz/craft3/storage/runtime/compiled_templates/fe/fe5d93ad3819b191310ce87199e7433a1a9d95be6b1c1c93c9550d78a418599f.php(46): Twig\Template->display()
#30 /home/abc/xyz/craft3/vendor/twig/twig/src/Template.php(405): __TwigTemplate_ca8e8f711c147ab2db82908f47b32c2885f0efe4f3f5100db9ad10988a8a3c5b->doDisplay()
#31 /home/abc/xyz/craft3/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#32 /home/abc/xyz/craft3/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#33 /home/abc/xyz/craft3/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#34 /home/abc/xyz/craft3/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#35 /home/abc/xyz/craft3/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render()
#36 /home/abc/xyz/craft3/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate()
#37 /home/abc/xyz/craft3/vendor/craftcms/cms/src/web/Controller.php(201): craft\web\View->renderPageTemplate()
#38 /home/abc/xyz/craft3/vendor/craftcms/cms/src/controllers/TemplatesController.php(102): craft\web\Controller->renderTemplate()
#39 [internal function]: craft\controllers\TemplatesController->actionRender()
#40 /home/abc/xyz/craft3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#41 /home/abc/xyz/craft3/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#42 /home/abc/xyz/craft3/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#43 /home/abc/xyz/craft3/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction()
#44 /home/abc/xyz/craft3/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#45 /home/abc/xyz/craft3/vendor/craftcms/cms/src/web/Application.php(278): yii\web\Application->handleRequest()
#46 /home/abc/xyz/craft3/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#47 /home/abc/xyz/htdocs/index.php(22): yii\base\Application->run()
#48 {main}
```

**Comment by kjmartens** [comment]
Sorry for the trouble @luke-nehemedia. Would you be able to try updating to 3.3.11 and see if it resolves the issue for you? If the error persists, would you be able to provide us with more information about your setup and template code? 🙂

**Comment by luke-nehemedia** [comment]
3.3.11 solved the issue. Thank you.
